title: "Trisha Das"
description: "PhD Student | Clinical Trials | AI for Healthcare"
baseurl: "" 
url: "https://trishad2.github.io"

author:
  name: "Trisha Das"
  email: "trishad2@illinois.edu"
  github: "trishad2"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  #- jekyll-scholar

scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: papers.bib

include: ["_pages"]
header_pages:
  - _pages/research.md
  - _pages/publications.md