title: "Trisha Das"
description: "PhD Student | Clinical Trials | AI for Healthcare"
baseurl: "" 
url: "https://username.github.io"

author:
  name: "Trisha Das"
  email: "your_email@university.edu"
  github: "username"
  linkedin: "your-linkedin"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: papers.bib
